name: Rust

on: ["push","pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Collect Coveralls Test Coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.coveralls_token }}
